// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OpStream.Server.Storage.MySQL;

#nullable disable

namespace OpStream.Server.Storage.MySQL.Migrations
{
    [DbContext(typeof(MySqlOpStreamDbContext))]
    partial class MySqlOpStreamDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("opstream")
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("OpStream.Server.Storage.EntityFrameworkCore.CommentEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("AnchorJson")
                        .HasColumnType("longtext");

                    b.Property<long>("AnchoredAtRevision")
                        .HasColumnType("bigint");

                    b.Property<string>("AuthorPeerId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DocumentId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("IsOrphaned")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ParentCommentId")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ResolvedByPeerId")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId", "ParentCommentId", "ResolvedAt");

                    b.ToTable("Comments", "opstream");
                });

            modelBuilder.Entity("OpStream.Server.Storage.EntityFrameworkCore.DocumentBranchEntity", b =>
                {
                    b.Property<string>("GlobalName")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("BranchId")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ForkParentBranchId")
                        .HasColumnType("longtext");

                    b.Property<long>("ForkRevision")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsReadOnly")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("PhysicalDocumentId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("GlobalName", "BranchId");

                    b.HasIndex("PhysicalDocumentId");

                    b.ToTable("DocumentBranches", "opstream");
                });

            modelBuilder.Entity("OpStream.Server.Storage.EntityFrameworkCore.DocumentNameEntity", b =>
                {
                    b.Property<string>("GlobalName")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DefaultBranchId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("EngineType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("GlobalName");

                    b.ToTable("DocumentNames", "opstream");
                });

            modelBuilder.Entity("OpStream.Server.Storage.EntityFrameworkCore.DocumentOpEntity", b =>
                {
                    b.Property<string>("DocumentId")
                        .HasColumnType("varchar(255)");

                    b.Property<long>("Revision")
                        .HasColumnType("bigint");

                    b.Property<string>("AuthorId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("EngineType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<byte[]>("Payload")
                        .IsRequired()
                        .HasColumnType("longblob");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("datetime(6)");

                    b.HasKey("DocumentId", "Revision");

                    b.HasIndex("DocumentId", "Revision");

                    b.ToTable("DocumentOps", "opstream");
                });

            modelBuilder.Entity("OpStream.Server.Storage.EntityFrameworkCore.DocumentSnapshotEntity", b =>
                {
                    b.Property<string>("DocumentId")
                        .HasColumnType("varchar(255)");

                    b.Property<long>("Revision")
                        .HasColumnType("bigint");

                    b.Property<byte[]>("State")
                        .IsRequired()
                        .HasColumnType("longblob");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("datetime(6)");

                    b.HasKey("DocumentId");

                    b.ToTable("DocumentSnapshots", "opstream");
                });

            modelBuilder.Entity("OpStream.Server.Storage.EntityFrameworkCore.DocumentVersionEntity", b =>
                {
                    b.Property<string>("GlobalName")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("BranchId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Tag")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("HistorySnapshotName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<long>("Revision")
                        .HasColumnType("bigint");

                    b.HasKey("GlobalName", "BranchId", "Tag");

                    b.HasIndex("GlobalName", "BranchId");

                    b.ToTable("DocumentVersions", "opstream");
                });

            modelBuilder.Entity("OpStream.Server.Storage.EntityFrameworkCore.HistoryOpEntity", b =>
                {
                    b.Property<string>("DocumentId")
                        .HasColumnType("varchar(255)");

                    b.Property<long>("Revision")
                        .HasColumnType("bigint");

                    b.Property<string>("AuthorId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("EngineType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<byte[]>("Payload")
                        .IsRequired()
                        .HasColumnType("longblob");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("datetime(6)");

                    b.HasKey("DocumentId", "Revision");

                    b.HasIndex("DocumentId", "Revision");

                    b.ToTable("HistoryOps", "opstream");
                });

            modelBuilder.Entity("OpStream.Server.Storage.EntityFrameworkCore.HistorySnapshotEntity", b =>
                {
                    b.Property<string>("DocumentId")
                        .HasColumnType("varchar(255)");

                    b.Property<long>("Revision")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<byte[]>("State")
                        .IsRequired()
                        .HasColumnType("longblob");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("datetime(6)");

                    b.HasKey("DocumentId", "Revision");

                    b.HasIndex("DocumentId", "Revision");

                    b.ToTable("HistorySnapshots", "opstream");
                });
#pragma warning restore 612, 618
        }
    }
}
