// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OpStream.Server.Storage.SQLite;

#nullable disable

namespace OpStream.Server.Storage.SQLite.Migrations
{
    [DbContext(typeof(SqliteOpStreamDbContext))]
    [Migration("20260529085317_UpdateModel")]
    partial class UpdateModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("OpStream.Server.Storage.EntityFrameworkCore.CommentEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AnchorJson")
                        .HasColumnType("TEXT");

                    b.Property<long>("AnchoredAtRevision")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AuthorPeerId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DocumentId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsOrphaned")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ParentCommentId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResolvedByPeerId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId", "ParentCommentId", "ResolvedAt");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("OpStream.Server.Storage.EntityFrameworkCore.DocumentBranchEntity", b =>
                {
                    b.Property<string>("GlobalName")
                        .HasColumnType("TEXT");

                    b.Property<string>("BranchId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ForkParentBranchId")
                        .HasColumnType("TEXT");

                    b.Property<long>("ForkRevision")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsReadOnly")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PhysicalDocumentId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("GlobalName", "BranchId");

                    b.HasIndex("PhysicalDocumentId");

                    b.ToTable("DocumentBranches");
                });

            modelBuilder.Entity("OpStream.Server.Storage.EntityFrameworkCore.DocumentNameEntity", b =>
                {
                    b.Property<string>("GlobalName")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultBranchId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EngineType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("GlobalName");

                    b.ToTable("DocumentNames");
                });

            modelBuilder.Entity("OpStream.Server.Storage.EntityFrameworkCore.DocumentOpEntity", b =>
                {
                    b.Property<string>("DocumentId")
                        .HasColumnType("TEXT");

                    b.Property<long>("Revision")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AuthorId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EngineType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Payload")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("DocumentId", "Revision");

                    b.HasIndex("DocumentId", "Revision");

                    b.ToTable("DocumentOps");
                });

            modelBuilder.Entity("OpStream.Server.Storage.EntityFrameworkCore.DocumentSnapshotEntity", b =>
                {
                    b.Property<string>("DocumentId")
                        .HasColumnType("TEXT");

                    b.Property<long>("Revision")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("State")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("DocumentId");

                    b.ToTable("DocumentSnapshots");
                });

            modelBuilder.Entity("OpStream.Server.Storage.EntityFrameworkCore.DocumentVersionEntity", b =>
                {
                    b.Property<string>("GlobalName")
                        .HasColumnType("TEXT");

                    b.Property<string>("BranchId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tag")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("HistorySnapshotName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("Revision")
                        .HasColumnType("INTEGER");

                    b.HasKey("GlobalName", "BranchId", "Tag");

                    b.HasIndex("GlobalName", "BranchId");

                    b.ToTable("DocumentVersions");
                });

            modelBuilder.Entity("OpStream.Server.Storage.EntityFrameworkCore.HistoryOpEntity", b =>
                {
                    b.Property<string>("DocumentId")
                        .HasColumnType("TEXT");

                    b.Property<long>("Revision")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AuthorId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EngineType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Payload")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("DocumentId", "Revision");

                    b.HasIndex("DocumentId", "Revision");

                    b.ToTable("HistoryOps");
                });

            modelBuilder.Entity("OpStream.Server.Storage.EntityFrameworkCore.HistorySnapshotEntity", b =>
                {
                    b.Property<string>("DocumentId")
                        .HasColumnType("TEXT");

                    b.Property<long>("Revision")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("State")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("DocumentId", "Revision");

                    b.HasIndex("DocumentId", "Revision");

                    b.ToTable("HistorySnapshots");
                });
#pragma warning restore 612, 618
        }
    }
}
